{
 "title": "Worker System",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Handled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(worker_requests_total{environment!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "count(worker_uptime_seconds)", "legendFormat": "env: {{environment}}" }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Gateway Bounces",
   "type": "timeseries",
   "description": "Bounce happens when the worker refuses the forwarded request because its request queue is full.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "sum(rate({container=\"request-gateway\"} |= \"has been bounced\" [1m])) * 60"
    }
   ]
  },
  {
   "title": "Gateway Timeouts",
   "type": "timeseries",
   "description": "Timeout means the gateway waited for the response too long. Either because the request took too long to execute, or some previous request on that worker did.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "sum(rate({container=\"request-gateway\"} |= \"has timed out on the worker system gateway\" [1m])) * 60"
    }
   ]
  },
  { "title": "Supervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Supervisor Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate({container=\"ws-supervisor\"}[10m]))"
    }
   ]
  },
  {
   "title": "Supervisor Issue Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate({container=\"ws-supervisor\"} != \"INFO\"[10m]))"
    }
   ]
  },
  {
   "title": "Supervisor Issues",
   "type": "logs",
   "description": "Anything logged that is not an INFO log.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{container=\"ws-supervisor\"} != \"INFO\""
    }
   ]
  }
 ]
}