{
 "title": "ArangoDB Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AQL Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_all_query[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AQL Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_slow_query[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}